name: DevOps Project CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t devops-website .
          echo "Docker image built successfully"

      # 3️ Test website
      - name: Test website
        run: |
          docker run -d -p 8080:80 --name test-container devops-website
          sleep 5
          curl -I http://localhost:8080

      # 4 Stop Docker container
      - name: Stop Docker container
        run: docker stop test-container

      # 5️ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
